### ISSUE TITLE
Rewrite marketing copy for launch

### ISSUE THREAD

**Issue by sarahmonster** [octopusthink/getmicdrop.com#13]
It could do with a bit of tightening up to be sure it flows well.

**Comment by sarahmonster** [comment]
Yeah, nevermind the beta copy. Let's just rewrite it with an actual launch in mind!

Draft outline here: https://www.notion.so/octopusthink/Marketing-site-2960e9b25722440d86d76c4fdde29ae6

And general guidance/thoughts/inspiration on marketing sites here: https://www.notion.so/octopusthink/Menubar-app-sites-56fe19c2bc714e5e9f43ecbf065d3915

**Comment by tofumatt** [comment]
This is… essentially complete. It's ongoing, but the site/Mac App Store listing are up.

So let's close this but continue to iterate as we always do. 😄
