### ISSUE TITLE
Create a post-purchase page for Paddle purchases

### ISSUE THREAD

**Issue by tofumatt** [octopusthink/getmicdrop.com#44]
We can customise the page a user is redirected to after they complete their purchase when buying via the website, so let's create a custom page to use instead of whatever the Paddle default is.

**Comment by sarahmonster** [comment]
I can take this on! Do we just want some nice thank-you text here?

**Comment by tofumatt** [comment]
Yeah, that'd be awesome. Maybe a link to the download as well (just re-use the download button).
