### ISSUE TITLE
Create an explainer video

### ISSUE THREAD

**Issue by sarahmonster** [octopusthink/getmicdrop.com#54]
For the website and other promotional materials, it would be nice to build a quick little explainer video that shows how Mic Drop works, especially since it is, in many way, something of a "hidden" app. (ie, there aren't many actual screens!)

I'm thinking showing someone in a video call on their computer, with a gallery of Brady-Bunch faces (maybe kittens? something cute but not human....), then showing them muting (and unmuting) as background noises interrupt, and maybe flipping through other apps/writing notes and muting as well?

Update: this is now in progress for reals! (Thanks @tofumatt!)

Here's what's left to do before we can launch it:
- [ ] add logos to "works with any app" (@sarahmonster)
- [ ] "always know if your mic is on" needs to Enrique window (@sarahmonster)
- [ ] add sounds (@tofumatt)
- [ ] animoji? (@tofumatt)
- [ ] figure out how/if we should animate talk bubbles (@sarahmonster)
- [ ] correct typography (@sarahmonster)

**Comment by sarahmonster** [comment]
UPDATE: this is done now, and it's good enough. 😅 

Do we want to add it to the website at all? If nothing else, we might want to swap out the kitten image for the emoji-meeting image....

**Comment by tofumatt** [comment]
Yes to the kitten > emoji 👍

I think adding it could be cute! I'm not sure where it'd go, but I'm game to add it if you can find a good place for it 🙂
