### ISSUE TITLE
Create a help page for the Monterey bug

### ISSUE THREAD

**Issue by dgauche** [octopusthink/getmicdrop.com#84]
Firstly, awesome app!!!

Recently I found that when you mute the mic it also mutes the speakers on my AirPods Pro.

MacBook Pro (16-inch, 2021)
MacOS 12.1 (21C52)
AirPods Pro (A2084) - Firmware: 4C165

This is repeatable across restarts.

Please let me know if you need anything else.
Thanks

**Comment by dgauche** [comment]
Sorry, I was in too much of a hurry to log a call. I now see this is only for your website.

My bad.

**Comment by tofumatt** [comment]
Oh, I forgot to mention it but we totally added this recently: https://getmicdrop.com/help/monterey-bluetooth

Even more exciting: we have a fix ready and will be shipping it this week! 🙂
